server.port: ${SERVER_PORT:8081}

spring:
  application:
    name: admin-web
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

gateway:
  url: ${GATEWAY_URL:http://localhost:8080}
